# Generated by Django 6.0.4 on 2026-04-09 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance')], default='operational', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='spaces.area')),
            ],
            options={
                'ordering': ['area', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SpaceOperatingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='spaces.space')),
            ],
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['area', 'floor'], name='spaces_spac_area_id_da52d1_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['status'], name='spaces_spac_status_c51728_idx'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('area', 'code'), name='spaces_space_unique_code_per_area'),
        ),
        migrations.AddConstraint(
            model_name='spaceoperatinghours',
            constraint=models.UniqueConstraint(fields=('space', 'day_of_week'), name='spaces_operating_hours_unique_day_per_space'),
        ),
    ]
