# Generated by Django 6.0.4 on 2026-04-09 21:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ReservationCreated', 'Reservation Created'), ('ReservationCancelled', 'Reservation Cancelled')], max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published_at', 'created_at'], name='reservation_publish_410e37_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space_id', models.UUIDField(db_index=True)),
                ('requester_user_id', models.UUIDField(db_index=True)),
                ('reservation_date', models.DateField()),
                ('start_hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('end_hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['space_id', 'reservation_date', 'status'], name='reservation_space_i_75b1bc_idx'), models.Index(fields=['requester_user_id', 'reservation_date'], name='reservation_request_7972a1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_hour__lt', models.F('end_hour'))), name='reservations_start_hour_before_end_hour'), models.CheckConstraint(condition=models.Q(('start_hour__gte', 0), ('start_hour__lte', 23)), name='reservations_start_hour_range'), models.CheckConstraint(condition=models.Q(('end_hour__gte', 1), ('end_hour__lte', 24)), name='reservations_end_hour_range')],
            },
        ),
    ]
